config/routes.rb
Rails.application.routes.draw do

  get 'calendars/index'
  resources :reportsheets
  get 'api/login'
  get 'api/heatmap'
  get 'api/idokeireport'
  post 'api/postposition'
  get 'api/getcomment'
  get 'api/get_microposts'
  get 'api/postmicropost'

  root 'freeaccess_pages#home'
  get '/help', to: 'freeaccess_pages#help'
  get '/about', to: 'freeaccess_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/add_positions_file', to: 'positions#add_file'
  get '/dmap', to: 'positions#dmap'
  post '/upload_position_file', to: 'positions#upload_file'
  get '/delete_all_positions', to: 'positions#delete_all'

  get 'calendars_view', to: 'calendars#index'
  get 'calendar_prev_month', to: 'calendars#index'
  get 'calendar_prev_years', to: 'calendars#index'
  get 'calendar_next_month', to: 'calendars#index'
  get 'calendar_next_years', to: 'calendars#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/reportsheet.rb
class Reportsheet < ApplicationRecord
  belongs_to :user
  has_many :positions, dependent: :destroy

  def add_geoposition(lats, lons, recdates, uid, rsid)
    #position = Position.where("user_id=?", uid).last
    #if position != nil
    #  (0..lats.count-1).each do |i|
      #  if recdates[i] >= position.recdate
    #      Position.create(reportsheet_id: rsid, lat: lats[i], lon: lons[i], recdate: recdates[i], user_id: uid)
      #  end
    #  end
    #else
      (0..lats.count-1).each do |i|
          Position.create(reportsheet_id: rsid, lat: lats[i], lon: lons[i], recdate: recdates[i], user_id: uid)
      end
    #end
  end
end

app/controllers/reportsheets_controller.rb
class ReportsheetsController < ApplicationController
  before_action :set_reportsheet, only: [:show, :edit, :update, :destroy]

  # GET /reportsheets
  # GET /reportsheets.json
  def index
    @reportsheets = Reportsheet.all
  end

  # GET /reportsheets/1
  # GET /reportsheets/1.json
  def show
  end

  # GET /reportsheets/new
  def new
    @reportsheet = Reportsheet.new
  end

  # GET /reportsheets/1/edit
  def edit
  end

  # POST /reportsheets
  # POST /reportsheets.json
  def create
    @reportsheet = Reportsheet.new(reportsheet_params)

    respond_to do |format|
      if @reportsheet.save
        format.html { redirect_to @reportsheet, notice: 'Reportsheet was successfully created.' }
        format.json { render :show, status: :created, location: @reportsheet }
      else
        format.html { render :new }
        format.json { render json: @reportsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reportsheets/1
  # PATCH/PUT /reportsheets/1.json
  def update
    respond_to do |format|
      if @reportsheet.update(reportsheet_params)
        format.html { redirect_to @reportsheet, notice: 'Reportsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @reportsheet }
      else
        format.html { render :edit }
        format.json { render json: @reportsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reportsheets/1
  # DELETE /reportsheets/1.json
  def destroy
    @reportsheet.destroy
    respond_to do |format|
      format.html { redirect_to reportsheets_url, notice: 'Reportsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reportsheet
      @reportsheet = Reportsheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reportsheet_params
      params.require(:reportsheet).permit(:user_id, :comment)
    end
end

app/helpers/reportsheets_helper.rb
module ReportsheetsHelper
end

app/views/reportsheets/_form.html.erb
<%= form_with(model: reportsheet, local: true) do |form| %>
  <% if reportsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reportsheet.errors.count, "error") %> prohibited this reportsheet from being saved:</h2>

      <ul>
        <% reportsheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reportsheets/edit.html.erb
<h1>Editing Reportsheet</h1>

<%= render 'form', reportsheet: @reportsheet %>

<%= link_to 'Show', @reportsheet %> |
<%= link_to 'Back', reportsheets_path %>

app/views/reportsheets/index.html.erb
<div class="col-md-12">
  <div class="row">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="row text-center">
    <div class="col-md-12">
      <h1>Reportsheets</h1>
    </div>
  </div>

  <div class="row text-center bg-info rounded">
    <div class="col-1">
      ユーザー ID
    </div>
    <div class="col-8">
      コメント
    </div>
    <div class="col-3">
      操作
    </div>
  </div>
  <% counter=0 %>
  <% @reportsheets.each do |reportsheet| %>
    <% if counter%2 == 0 %>
      <div class="row border-bottom border-warning">
    <% else %>
      <div class="row border-bottom border-info">
    <% end %>
      <div class="col-1 text-center"><%= reportsheet.user_id %></div>
      <div class="col-8"><%= reportsheet.comment %></div>
      <div class="col-1 pl-0"><%= link_to '表示', reportsheet, class: "btn btn-outline-primary btn-block btn-sm", role: "button" %></div>
      <div class="col-1 pl-0"><%= link_to '編集', edit_reportsheet_path(reportsheet), class: "btn btn-outline-secondary btn-block btn-sm", role: "button" %></div>
      <div class="col-1 pl-0"><%= link_to '削除', reportsheet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-block btn-sm", role: "button" %></div>
    </div>
    <% counter += 1 %>
  <% end %>
  <br/>
  <%= link_to 'New Reportsheet', new_reportsheet_path, class: "btn btn-outline-primary", role: "button" %>
</div>

app/views/reportsheets/new.html.erb
<h1>New Reportsheet</h1>

<%= render 'form', reportsheet: @reportsheet %>

<%= link_to 'Back', reportsheets_path %>

app/views/reportsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reportsheet.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reportsheet.comment %>
</p>

<%= link_to 'Edit', edit_reportsheet_path(@reportsheet) %> |
<%= link_to 'Back', reportsheets_path %>