config/routes.rb
Rails.application.routes.draw do

  get 'calendars/index'
  resources :reportsheets
  get 'api/login'
  get 'api/heatmap'
  get 'api/idokeireport'
  post 'api/postposition'
  get 'api/getcomment'
  get 'api/get_microposts'
  get 'api/postmicropost'

  root 'freeaccess_pages#home'
  get '/help', to: 'freeaccess_pages#help'
  get '/about', to: 'freeaccess_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/add_positions_file', to: 'positions#add_file'
  get '/dmap', to: 'positions#dmap'
  post '/upload_position_file', to: 'positions#upload_file'
  get '/delete_all_positions', to: 'positions#delete_all'

  get 'calendars_view', to: 'calendars#index'
  get 'calendar_prev_month', to: 'calendars#index'
  get 'calendar_prev_years', to: 'calendars#index'
  get 'calendar_next_month', to: 'calendars#index'
  get 'calendar_next_years', to: 'calendars#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    selDate = params[:selDate]
    if selDate == nil || selDate == ""
      currentDate = DateTime.now
    else
      currentDate = Date.parse selDate
    end
    @month = currentDate.strftime("%m").to_i
    @year = currentDate.strftime("%Y").to_i
    firstday = currentDate.strftime("%y/%m/")+"1"
    @fday = Date.parse firstday
    daystr = @fday.strftime("%a")

    day = 0
    pmday = 0

    @box = Array.new(42)

    case @month
    when 2
      if @year%4 == 0
        day = 29
      else
        day = 28
      end
      pmday = 31
    when 4,6,9,11
      day = 30
      pmday = 31
    when 1,5,7,10,12
      day = 31
      pmday = 30
    when 8
      day = 31
      pmday = 31
    else
      day = 31
      if @year%4 == 0
        pmday = 29
      else
        pmday = 28
      end
    end

    startcount = 0
    case daystr
    when "Mon"
      @box[0] = "" #pmday
      startcount = 1
    when  "Tue"
      @box[0] = "" #pmday-1
      @box[1] = "" #pmday
      startcount = 2
    when "Wed"
      for i in 0..2 do
        @box[i] = "" #pmday - (2 - i)
      end
      startcount = 3
    when "Thu"
      for i in 0..3 do
        @box[i] = ""#pmday - (3 - i)
      end
      startcount = 4
    when "Fri"
      for i in 0..4 do
        @box[i] = ""#pmday - (4 - i)
      end
      startcount = 5
    when "Sat"
      for i in 0..5 do
        @box[i] = "" #pmday - (5 - i)
      end
      startcount = 6
    else
      startcount = 0
    end


    counter = 0
    for i in startcount..41 do
      counter += 1
      @box[i] = counter
      if counter > day
        #counter = 1
        @box[i] = ""
      end
    end
    @test = @month
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_calendar.html.erb
<div class="border-right border-bottom border-left">
  <br/>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-1 text-center">
      <%= link_to "去年", calendar_prev_years_path(:selDate => @fday - 1.years), class: "btn btn-primary btn-sm", role: "button" %>
    </div>
    <div class="col-1 text-center">
      <%= link_to "先月", calendar_prev_month_path(:selDate => @fday - 1.months), class: "btn btn-info btn-sm", role: "button" %>
    </div>
    <div class="col-3 text-center">
      <h1><%=@year%>年<%=@month%>月</h1>
    </div>
    <div class="col-1 text-center">
      <%= link_to "来月", calendar_next_month_path(:selDate => @fday + 1.months), class: "btn btn-info btn-sm", role: "button" %>
    </div>
    <div class="col-1 text-center">
      <%= link_to "来年", calendar_next_years_path(:selDate => @fday + 1.years), class: "btn btn-primary btn-sm", role: "botton" %>
    </div>
  </div>
  <div class="row ">
    <div class="col-2">
    </div>
    <div class="col-1 border text-center text-danger">
      日曜日
    </div>
    <div class="col-1 border text-center">
      月曜日
    </div>
    <div class="col-1 border text-center">
      火曜日
    </div>
    <div class="col-1 border text-center">
      水曜日
    </div>
    <div class="col-1 border text-center">
      木曜日
    </div>
    <div class="col-1 border text-center">
      金曜日
    </div>
    <div class="col-1 border text-center">
      土曜日
    </div>
    <div class="col-3">
    </div>
  </div>
  <% counter = 0 %>
  <% for i in 0..5 do %>
    <div class="row">
      <div class="col-2">
      </div>
      <% for j in 0..6 do %>
        <% if j == 0 %>
          <div class="col-1 border text-danger">
        <% else %>
          <div class="col-1 border">
        <% end %>
          <%= @box[counter] %>
          <% counter += 1 %>
        </div>
      <% end %>
      <div class="col-3">
      </div>
    </div>
  <% end %>


  <br/>
</div>

app/views/calendars/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xl-12">
    <ul class="nav nav-tabs" id="mytab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="not-related" data-toggle="tab" href="#torikomi" role="tab" aria-controls="not-related" aria-selected="true">自分</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="not-related" data-toggle="tab" href="#family" role="tab" aria-controls="not-related" aria-selected="false">家族</a>
      </li>

    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="torikomi" role="tabpanel" aria-labelled="not-related">
        <%= render 'calendar' %>
      </div>
      <div class="tab-pane fade" id="family" role="tabpanel" aria-labelled="not-related">
        家族
      </div>
    </div>
  </div>
</div>
</div>