config/routes.rb
Rails.application.routes.draw do

  get 'calendars/index'
  resources :reportsheets
  get 'api/login'
  get 'api/heatmap'
  get 'api/idokeireport'
  post 'api/postposition'
  get 'api/getcomment'
  get 'api/get_microposts'
  get 'api/postmicropost'

  root 'freeaccess_pages#home'
  get '/help', to: 'freeaccess_pages#help'
  get '/about', to: 'freeaccess_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/add_positions_file', to: 'positions#add_file'
  get '/dmap', to: 'positions#dmap'
  post '/upload_position_file', to: 'positions#upload_file'
  get '/delete_all_positions', to: 'positions#delete_all'

  get 'calendars_view', to: 'calendars#index'
  get 'calendar_prev_month', to: 'calendars#index'
  get 'calendar_prev_years', to: 'calendars#index'
  get 'calendar_next_month', to: 'calendars#index'
  get 'calendar_next_years', to: 'calendars#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>
    The Medical API by<%= image_tag("sbs_logo.png", alt: "sbs logo", size: "80x20", id:"sbs_logo")%>
  </small>
  <nav>
    <ul>
      <small>
        <li><%= link_to "連絡先", about_path %></li>
      </small>
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top shadow p-1 mb-3 rounded">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>" id="medical_title">
      <%= image_tag("phi.png", alt: "phi logo", size: "30x30", id:"phi_logo")%>Medical API
    </a>
    <nav>
      <ul class="nav">
        <li class="nav-item"><%= link_to "ホーム", root_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "ヘルプ", help_path, class: "nav-link" %></li>
        <% if logged_in? %>
          <% #if current_user.admin? %>
            <li class="nav-item"><%= link_to "ユーザー", users_path, class: "nav-link" %></li>
          <% #end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              アンケート<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <a><li><%= link_to "新規アンケート","#" %></li></a>
              <li><%= link_to "アンケート一覧","#" %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              ツール<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <a class="nav-link" href="<%= reportsheets_path %>">報告書</a>
              <a class="nav-link" href="<%= dmap_path %>">行動</a>
              <li class="dropdown-divider"></li>
              <a class="nav-link" href="<%= calendars_view_path %>">日記</a>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

              <a class="nav-link" href="<%=current_user%>">プロファイル</a>
              <a class="nav-link" href="<%=edit_user_path(current_user)%>">設定</a>
              <li class="dropdown-divider"></li>
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
                integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
                crossorigin=""/>
<script src="https://cdn.jsdelivr.net/npm/leaflet-heatmap@1.0.0/leaflet-heatmap.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>